use crate::engine::schema::*;

pub fn register(r: &mut Registry) {
    r.add_module(ModuleDef {
        key: "hr",
        label: "People",
        icon: "UserCog",
        color: "purple",
        description: "Employees, departments and leave.",
    });

    r.add(EntityDef {
        key: "hr.departments",
        table: "departments",
        module: "hr",
        label: "Department",
        label_plural: "Departments",
        icon: "Network",
        title_field: "name",
        fields: vec![
            text("name", "Department").required().in_list(),
            text("code", "Code").in_list(),
            reference("head_id", "Head", "hr.employees").in_list(),
            long_text("description", "Description"),
        ],
        default_sort: ("name", SortDir::Asc),
        children: vec![ChildDef {
            entity: "hr.employees",
            foreign_key: "department_id",
            label: "Employees",
            inline: false,
        }],
        has_activities: false,
        has_notes: false,
        global_search: true,
        embedded: false,
        read_only: false,
    });

    r.add(EntityDef {
        key: "hr.employees",
        table: "employees",
        module: "hr",
        label: "Employee",
        label_plural: "Employees",
        icon: "IdCard",
        title_field: "full_name",
        fields: vec![
            text("full_name", "Name").required().in_list(),
            text("employee_code", "Employee ID").in_list(),
            email("work_email", "Work email").in_list(),
            email("personal_email", "Personal email"),
            phone("phone", "Phone"),
            reference("user_id", "Login", "core.users"),
            reference("department_id", "Department", "hr.departments").in_list(),
            text("designation", "Designation").in_list(),
            reference("manager_id", "Manager", "hr.employees").in_list(),
            select("employment_type", "Employment", vec![
                opt("full_time", "Full time", "brand"),
                opt("part_time", "Part time", "info"),
                opt("contract", "Contract", "warning"),
                opt("intern", "Intern", "purple"),
            ]).required().with_default("full_time").in_list(),
            select("status", "Status", vec![
                opt("active", "Active", "success"),
                opt("on_leave", "On leave", "warning"),
                opt("notice", "Notice period", "danger"),
                opt("exited", "Exited", "neutral"),
            ]).required().with_default("active").in_list(),
            date("date_of_joining", "Joined").in_list(),
            date("date_of_birth", "Date of birth"),
            money("annual_salary", "Annual salary"),
            text("location", "Location").in_list().suggests(),
            long_text("notes", "Notes"),
        ],
        default_sort: ("full_name", SortDir::Asc),
        children: vec![ChildDef {
            entity: "hr.leave_requests",
            foreign_key: "employee_id",
            label: "Leave",
            inline: false,
        }],
        has_activities: false,
        has_notes: true,
        global_search: true,
        embedded: false,
        read_only: false,
    });

    r.add(EntityDef {
        key: "hr.leave_requests",
        table: "leave_requests",
        module: "hr",
        label: "Leave request",
        label_plural: "Leave",
        icon: "CalendarOff",
        title_field: "reason",
        fields: vec![
            reference("employee_id", "Employee", "hr.employees").required().in_list(),
            select("leave_type", "Type", vec![
                opt("annual", "Annual", "brand"),
                opt("sick", "Sick", "danger"),
                opt("unpaid", "Unpaid", "neutral"),
                opt("parental", "Parental", "purple"),
                opt("comp_off", "Comp off", "info"),
            ]).required().with_default("annual").in_list(),
            select("status", "Status", vec![
                opt("pending", "Pending", "warning"),
                opt("approved", "Approved", "success"),
                opt("rejected", "Rejected", "danger"),
                opt("cancelled", "Cancelled", "neutral"),
            ]).required().with_default("pending").in_list(),
            date("start_date", "From").required().in_list(),
            date("end_date", "To").required().in_list(),
            quantity("days", "Days").in_list(),
            text("reason", "Reason").in_list(),
            reference("approver_id", "Approver", "core.users"),
            datetime("decided_at", "Decided at").readonly(),
        ],
        default_sort: ("start_date", SortDir::Desc),
        children: vec![],
        has_activities: false,
        has_notes: false,
        global_search: false,
        embedded: false,
        read_only: false,
    });

    r.add(EntityDef {
        key: "hr.shifts",
        table: "shifts",
        module: "hr",
        label: "Shift",
        label_plural: "Shifts",
        icon: "CalendarClock",
        title_field: "shift_date",
        fields: vec![
            reference("employee_id", "Employee", "hr.employees").required().in_list(),
            date("shift_date", "Date").required().in_list(),
            datetime("starts_at", "Starts").required().in_list(),
            datetime("ends_at", "Ends").required().in_list(),
            select("status", "Status", vec![
                opt("scheduled", "Scheduled", "info"),
                opt("published", "Published", "success"),
                opt("cancelled", "Cancelled", "neutral"),
            ]).required().with_default("scheduled").in_list(),
            text("role_note", "Covering").suggests().in_list(),
        ],
        default_sort: ("shift_date", SortDir::Desc),
        children: vec![],
        has_activities: false,
        has_notes: false,
        global_search: false,
        embedded: false,
        read_only: false,
    });

    r.add(EntityDef {
        key: "hr.attendance",
        table: "attendance",
        module: "hr",
        label: "Attendance",
        label_plural: "Attendance",
        icon: "Clock",
        title_field: "work_date",
        fields: vec![
            reference("employee_id", "Employee", "hr.employees").required().in_list(),
            date("work_date", "Date").required().in_list(),
            datetime("clock_in", "Clocked in").in_list(),
            datetime("clock_out", "Clocked out").in_list(),
            // Derived from the two stamps above on every write, so a corrected
            // clock-out cannot leave a stale total behind it.
            int("worked_minutes", "Minutes worked").readonly().in_list(),
            select("status", "Status", vec![
                opt("present", "Present", "success"),
                opt("late", "Late", "warning"),
                opt("absent", "Absent", "danger"),
                opt("on_leave", "On leave", "info"),
                opt("holiday", "Holiday", "neutral"),
            ]).required().with_default("present").in_list(),
            reference("shift_id", "Against shift", "hr.shifts"),
            text("notes", "Notes"),
        ],
        default_sort: ("work_date", SortDir::Desc),
        children: vec![],
        has_activities: false,
        has_notes: false,
        global_search: false,
        embedded: false,
        read_only: false,
    });

    r.add(EntityDef {
        key: "hr.pay_runs",
        table: "pay_runs",
        module: "hr",
        label: "Pay run",
        label_plural: "Pay runs",
        icon: "Banknote",
        title_field: "reference",
        fields: vec![
            text("reference", "Run").required().in_list(),
            date("period_start", "From").required().in_list(),
            date("period_end", "To").required().in_list(),
            date("pay_date", "Pay date").in_list(),
            select("status", "Status", vec![
                opt("draft", "Draft", "neutral"),
                opt("approved", "Approved", "info"),
                opt("paid", "Paid", "success"),
            ]).required().with_default("draft").in_list(),
            money("total_gross", "Gross").readonly().in_list(),
            money("total_net", "Net").readonly().in_list(),
            long_text("notes", "Notes"),
        ],
        default_sort: ("period_start", SortDir::Desc),
        children: vec![ChildDef {
            entity: "hr.payslips",
            foreign_key: "pay_run_id",
            label: "Payslips",
            inline: false,
        }],
        has_activities: false,
        has_notes: false,
        global_search: true,
        embedded: false,
        read_only: false,
    });

    r.add(EntityDef {
        key: "hr.payslips",
        table: "payslips",
        module: "hr",
        label: "Payslip",
        label_plural: "Payslips",
        icon: "ReceiptText",
        title_field: "slip_for",
        fields: vec![
            reference("pay_run_id", "Pay run", "hr.pay_runs").required().in_list(),
            reference("employee_id", "Employee", "hr.employees").required().in_list(),
            // Who and which period, composed on write so a slip is identifiable
            // in a list without joining back to two other tables.
            text("slip_for", "Payslip").readonly().in_list(),
            money("gross", "Gross").in_list(),
            money("deductions", "Deductions").in_list(),
            money("net", "Net").readonly().in_list(),
            // Pulled from the attendance already recorded for the run's period,
            // so the hours behind the payment are visible on the payment.
            int("minutes_worked", "Minutes worked").readonly().in_list(),
            long_text("notes", "Notes"),
        ],
        default_sort: ("created_at", SortDir::Desc),
        children: vec![],
        has_activities: false,
        has_notes: false,
        global_search: false,
        embedded: false,
        read_only: false,
    });
}
